#!/bin/bash
# Publishes updates to website on stroberg-lab.github.io
# Copies static site file generated by hugo to the master site directory
# and pushes the update to GitHub. 
# Static files must first be generated by running 'hugo' in the website source directory

SITEMASTER="/Users/wyliestroberg/Documents/GitHub/stroberg-lab.github.io" # Site root dir
STATIC="/Users/wyliestroberg/Documents/GitHub/lab-website-hugo/public" # Dir with static site content

# Copy static files to site master root directory
cp -r ${STATIC}/* ${SITEMASTER}

# Commit and Push updated website
cd $SITEMASTER
git add * :/
git commit -m 'website update'
git push -u origin master

